name: Deploy
on:
  - push
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn run static
      - uses: actions/upload-artifact@v2
        with:
          name: ochranaovci.cz
          path: out/
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "out"
          remoteDir: "www"
